-- Crear la tabla de usuarios
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    email VARCHAR2(100)
);

-- Insertar datos en la tabla de usuarios
INSERT INTO usuarios (nombre, email) VALUES
('Caceres Hilasaca', 'cacereshilasacajhack@gmail.com');

INSERT INTO usuarios (nombre, email) VALUES
('Margarita Hilasaca', 'margaritahilasaca@gmail.com');


ROLLBACK;

-- Para ver la estructura de la tabla USUARIOS
DESCRIBE USUARIOS;

DROP TABLE usuarios;
DROP TABLE USUARIOS;

-- Eliminar la tabla si existe
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE usuarios';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- Crear la tabla de usuarios
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    email VARCHAR2(100)
);

-- Insertar datos en la tabla de usuarios
INSERT INTO usuarios (nombre, email) VALUES
('Caceres Hilasaca', 'cacereshilasacajhack@gmail.com');

INSERT INTO usuarios (nombre, email) VALUES
('Margarita Hilasaca', 'margaritahilasaca@gmail.com');

